### ISSUE TITLE
Support the new apt/rpm repo URLs

### ISSUE THREAD

**Issue by drewhammond** [sous-chefs/chef-grafana#421]
## :ghost: Brief Description

On Nov 8, 2022, Grafana changed the URL of their repos.

https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/#repository-migration-november-8th-2022

>From that date, Grafana packages will be served from a new repository (<packages.grafana.com/deb/{product}> -> <apt.grafana.com>). The new repository serves, from a single APT configuration, all Grafana OSS products, as well as Grafana Enterprise.

>The old URLs will still work, serving the content from the new repository, but you may encounter warnings about some repository attributes changing (e.g. Origin and Label).

https://grafana.com/docs/grafana/latest/setup-grafana/installation/rpm/#repository-migration-november-8th-2022

>From that date, Grafana packages will be served from a new repository (<packages.grafana.com/rpm/{product}> -> <rpm.grafana.com>). The new repository serves, from a single YUM/DNF configuration, all Grafana OSS products, as well as Grafana Enterprise.

>The old URLs will still work, serving the content from the new repository, but you may encounter warnings about some repository attributes changing.

**Comment by bmhughes** [comment]
Picked this up in #420

**Comment by bmhughes** [comment]
Released in 10.2.0
